info: Server started at http://localhost:3000/api/v1/ {"timestamp":"2022-05-30T03:30:03.746Z"}
info: Connected to the database. {"timestamp":"2022-05-30T03:30:03.866Z"}
info: Server started at http://localhost:3000/api/v1/ {"timestamp":"2022-05-30T03:39:32.174Z"}
info: Connected to the database. {"timestamp":"2022-05-30T03:39:32.275Z"}
info: Server started at http://localhost:3000/api/v1/ {"timestamp":"2022-05-30T03:42:16.110Z"}
info: Connected to the database. {"timestamp":"2022-05-30T03:42:16.180Z"}
error: 
    status - 500 
    message - Error: secretOrPrivateKey must have a value
    at Object.sign (C:\Users\user\Desktop\FundooNotes\FundooNotes\node_modules\jsonwebtoken\sign.js:107:20)
    at _callee3$ (C:\Users\user\Desktop\FundooNotes\FundooNotes\src\services\/user.service.js:29:23)
    at tryCatch (C:\Users\user\Desktop\FundooNotes\FundooNotes\node_modules\@babel\runtime\helpers\regeneratorRuntime.js:86:17)
    at Generator._invoke (C:\Users\user\Desktop\FundooNotes\FundooNotes\node_modules\@babel\runtime\helpers\regeneratorRuntime.js:66:24)
    at Generator.next (C:\Users\user\Desktop\FundooNotes\FundooNotes\node_modules\@babel\runtime\helpers\regeneratorRuntime.js:117:21)
    at asyncGeneratorStep (C:\Users\user\Desktop\FundooNotes\FundooNotes\node_modules\@babel\runtime\helpers\asyncToGenerator.js:3:24)
    at _next (C:\Users\user\Desktop\FundooNotes\FundooNotes\node_modules\@babel\runtime\helpers\asyncToGenerator.js:25:9) 
    url - /api/v1/users/login 
    method - POST 
    IP - ::1
   {"timestamp":"2022-05-30T03:42:32.717Z"}
error: 
    status - 500 
    message - Error: secretOrPrivateKey must have a value
    at Object.sign (C:\Users\user\Desktop\FundooNotes\FundooNotes\node_modules\jsonwebtoken\sign.js:107:20)
    at _callee3$ (C:\Users\user\Desktop\FundooNotes\FundooNotes\src\services\/user.service.js:29:23)
    at tryCatch (C:\Users\user\Desktop\FundooNotes\FundooNotes\node_modules\@babel\runtime\helpers\regeneratorRuntime.js:86:17)
    at Generator._invoke (C:\Users\user\Desktop\FundooNotes\FundooNotes\node_modules\@babel\runtime\helpers\regeneratorRuntime.js:66:24)
    at Generator.next (C:\Users\user\Desktop\FundooNotes\FundooNotes\node_modules\@babel\runtime\helpers\regeneratorRuntime.js:117:21)
    at asyncGeneratorStep (C:\Users\user\Desktop\FundooNotes\FundooNotes\node_modules\@babel\runtime\helpers\asyncToGenerator.js:3:24)
    at _next (C:\Users\user\Desktop\FundooNotes\FundooNotes\node_modules\@babel\runtime\helpers\asyncToGenerator.js:25:9) 
    url - /api/v1/users/login 
    method - POST 
    IP - ::1
   {"timestamp":"2022-05-30T03:43:30.593Z"}
info: Server started at http://localhost:3000/api/v1/ {"timestamp":"2022-05-30T03:44:14.282Z"}
info: Connected to the database. {"timestamp":"2022-05-30T03:44:14.374Z"}
info: Server started at http://localhost:3000/api/v1/ {"timestamp":"2022-05-30T03:55:49.203Z"}
info: Connected to the database. {"timestamp":"2022-05-30T03:55:49.263Z"}
info: Server started at http://localhost:3000/api/v1/ {"timestamp":"2022-05-30T03:58:25.471Z"}
info: Connected to the database. {"timestamp":"2022-05-30T03:58:25.555Z"}
info: Server started at http://localhost:3000/api/v1/ {"timestamp":"2022-05-30T04:02:29.039Z"}
info: Connected to the database. {"timestamp":"2022-05-30T04:02:29.106Z"}
info: Server started at http://localhost:3000/api/v1/ {"timestamp":"2022-05-30T04:03:24.341Z"}
info: Connected to the database. {"timestamp":"2022-05-30T04:03:24.465Z"}
info: Server started at http://localhost:3000/api/v1/ {"timestamp":"2022-05-30T04:41:05.361Z"}
info: Connected to the database. {"timestamp":"2022-05-30T04:41:05.470Z"}
error: 
    status - 500 
    message - Error: User does not exist
    at _callee3$ (C:\Users\user\Desktop\FundooNotes\FundooNotes\src\services\/user.service.js:25:11)
    at tryCatch (C:\Users\user\Desktop\FundooNotes\FundooNotes\node_modules\@babel\runtime\helpers\regeneratorRuntime.js:86:17)
    at Generator._invoke (C:\Users\user\Desktop\FundooNotes\FundooNotes\node_modules\@babel\runtime\helpers\regeneratorRuntime.js:66:24)
    at Generator.next (C:\Users\user\Desktop\FundooNotes\FundooNotes\node_modules\@babel\runtime\helpers\regeneratorRuntime.js:117:21)
    at asyncGeneratorStep (C:\Users\user\Desktop\FundooNotes\FundooNotes\node_modules\@babel\runtime\helpers\asyncToGenerator.js:3:24)
    at _next (C:\Users\user\Desktop\FundooNotes\FundooNotes\node_modules\@babel\runtime\helpers\asyncToGenerator.js:25:9)
    at processTicksAndRejections (node:internal/process/task_queues:96:5) 
    url - /api/v1/users/login 
    method - POST 
    IP - ::1
   {"timestamp":"2022-05-30T04:41:20.150Z"}
info: Connected to the database. {"timestamp":"2022-05-30T04:44:24.531Z"}
info: Server started at http://localhost:3000/api/v1/ {"timestamp":"2022-05-30T04:45:06.050Z"}
info: Connected to the database. {"timestamp":"2022-05-30T04:45:06.162Z"}
info: Server started at http://localhost:3000/api/v1/ {"timestamp":"2022-05-30T06:35:17.747Z"}
info: Connected to the database. {"timestamp":"2022-05-30T06:35:17.830Z"}
info: Server started at http://localhost:3000/api/v1/ {"timestamp":"2022-05-30T06:38:35.547Z"}
info: Connected to the database. {"timestamp":"2022-05-30T06:38:35.610Z"}
info: Server started at http://localhost:3000/api/v1/ {"timestamp":"2022-05-30T06:40:09.947Z"}
info: Connected to the database. {"timestamp":"2022-05-30T06:40:10.020Z"}
info: Server started at http://localhost:3000/api/v1/ {"timestamp":"2022-05-30T06:47:50.093Z"}
info: Connected to the database. {"timestamp":"2022-05-30T06:47:50.184Z"}
error: 
    status - 500 
    message - SyntaxError: Unexpected end of JSON input
    at JSON.parse (<anonymous>)
    at createStrictSyntaxError (C:\Users\user\Desktop\FundooNotes\FundooNotes\node_modules\body-parser\lib\types\json.js:160:10)
    at parse (C:\Users\user\Desktop\FundooNotes\FundooNotes\node_modules\body-parser\lib\types\json.js:83:15)
    at C:\Users\user\Desktop\FundooNotes\FundooNotes\node_modules\body-parser\lib\read.js:128:18
    at AsyncResource.runInAsyncScope (node:async_hooks:202:9)
    at invokeCallback (C:\Users\user\Desktop\FundooNotes\FundooNotes\node_modules\raw-body\index.js:231:16)
    at done (C:\Users\user\Desktop\FundooNotes\FundooNotes\node_modules\raw-body\index.js:220:7)
    at IncomingMessage.onEnd (C:\Users\user\Desktop\FundooNotes\FundooNotes\node_modules\raw-body\index.js:280:7)
    at IncomingMessage.emit (node:events:539:35)
    at IncomingMessage.emit (node:domain:475:12)
    at endReadableNT (node:internal/streams/readable:1345:12)
    at processTicksAndRejections (node:internal/process/task_queues:83:21) 
    url - /api/v1/users 
    method - POST 
    IP - ::1
   {"timestamp":"2022-05-30T06:49:53.619Z"}
error: 
    status - 500 
    message - SyntaxError: Unexpected end of JSON input
    at JSON.parse (<anonymous>)
    at createStrictSyntaxError (C:\Users\user\Desktop\FundooNotes\FundooNotes\node_modules\body-parser\lib\types\json.js:160:10)
    at parse (C:\Users\user\Desktop\FundooNotes\FundooNotes\node_modules\body-parser\lib\types\json.js:83:15)
    at C:\Users\user\Desktop\FundooNotes\FundooNotes\node_modules\body-parser\lib\read.js:128:18
    at AsyncResource.runInAsyncScope (node:async_hooks:202:9)
    at invokeCallback (C:\Users\user\Desktop\FundooNotes\FundooNotes\node_modules\raw-body\index.js:231:16)
    at done (C:\Users\user\Desktop\FundooNotes\FundooNotes\node_modules\raw-body\index.js:220:7)
    at IncomingMessage.onEnd (C:\Users\user\Desktop\FundooNotes\FundooNotes\node_modules\raw-body\index.js:280:7)
    at IncomingMessage.emit (node:events:539:35)
    at IncomingMessage.emit (node:domain:475:12)
    at endReadableNT (node:internal/streams/readable:1345:12)
    at processTicksAndRejections (node:internal/process/task_queues:83:21) 
    url - /api/v1/users 
    method - POST 
    IP - ::1
   {"timestamp":"2022-05-30T06:50:14.374Z"}
error: 
    status - 500 
    message - SyntaxError: Unexpected end of JSON input
    at JSON.parse (<anonymous>)
    at createStrictSyntaxError (C:\Users\user\Desktop\FundooNotes\FundooNotes\node_modules\body-parser\lib\types\json.js:160:10)
    at parse (C:\Users\user\Desktop\FundooNotes\FundooNotes\node_modules\body-parser\lib\types\json.js:83:15)
    at C:\Users\user\Desktop\FundooNotes\FundooNotes\node_modules\body-parser\lib\read.js:128:18
    at AsyncResource.runInAsyncScope (node:async_hooks:202:9)
    at invokeCallback (C:\Users\user\Desktop\FundooNotes\FundooNotes\node_modules\raw-body\index.js:231:16)
    at done (C:\Users\user\Desktop\FundooNotes\FundooNotes\node_modules\raw-body\index.js:220:7)
    at IncomingMessage.onEnd (C:\Users\user\Desktop\FundooNotes\FundooNotes\node_modules\raw-body\index.js:280:7)
    at IncomingMessage.emit (node:events:539:35)
    at IncomingMessage.emit (node:domain:475:12)
    at endReadableNT (node:internal/streams/readable:1345:12)
    at processTicksAndRejections (node:internal/process/task_queues:83:21) 
    url - /api/v1/users/ 
    method - GET 
    IP - ::1
   {"timestamp":"2022-05-30T06:50:25.262Z"}
error: 
    status - 500 
    message - SyntaxError: Unexpected end of JSON input
    at JSON.parse (<anonymous>)
    at createStrictSyntaxError (C:\Users\user\Desktop\FundooNotes\FundooNotes\node_modules\body-parser\lib\types\json.js:160:10)
    at parse (C:\Users\user\Desktop\FundooNotes\FundooNotes\node_modules\body-parser\lib\types\json.js:83:15)
    at C:\Users\user\Desktop\FundooNotes\FundooNotes\node_modules\body-parser\lib\read.js:128:18
    at AsyncResource.runInAsyncScope (node:async_hooks:202:9)
    at invokeCallback (C:\Users\user\Desktop\FundooNotes\FundooNotes\node_modules\raw-body\index.js:231:16)
    at done (C:\Users\user\Desktop\FundooNotes\FundooNotes\node_modules\raw-body\index.js:220:7)
    at IncomingMessage.onEnd (C:\Users\user\Desktop\FundooNotes\FundooNotes\node_modules\raw-body\index.js:280:7)
    at IncomingMessage.emit (node:events:539:35)
    at IncomingMessage.emit (node:domain:475:12)
    at endReadableNT (node:internal/streams/readable:1345:12)
    at processTicksAndRejections (node:internal/process/task_queues:83:21) 
    url - /api/v1/users/ 
    method - GET 
    IP - ::1
   {"timestamp":"2022-05-30T06:50:38.160Z"}
error: 
    status - 500 
    message - SyntaxError: Unexpected end of JSON input
    at JSON.parse (<anonymous>)
    at createStrictSyntaxError (C:\Users\user\Desktop\FundooNotes\FundooNotes\node_modules\body-parser\lib\types\json.js:160:10)
    at parse (C:\Users\user\Desktop\FundooNotes\FundooNotes\node_modules\body-parser\lib\types\json.js:83:15)
    at C:\Users\user\Desktop\FundooNotes\FundooNotes\node_modules\body-parser\lib\read.js:128:18
    at AsyncResource.runInAsyncScope (node:async_hooks:202:9)
    at invokeCallback (C:\Users\user\Desktop\FundooNotes\FundooNotes\node_modules\raw-body\index.js:231:16)
    at done (C:\Users\user\Desktop\FundooNotes\FundooNotes\node_modules\raw-body\index.js:220:7)
    at IncomingMessage.onEnd (C:\Users\user\Desktop\FundooNotes\FundooNotes\node_modules\raw-body\index.js:280:7)
    at IncomingMessage.emit (node:events:539:35)
    at IncomingMessage.emit (node:domain:475:12)
    at endReadableNT (node:internal/streams/readable:1345:12)
    at processTicksAndRejections (node:internal/process/task_queues:83:21) 
    url - /api/v1/users/ 
    method - GET 
    IP - ::1
   {"timestamp":"2022-05-30T06:50:44.699Z"}
error: 
    status - 500 
    message - ReferenceError: User is not defined
    at _callee$ (C:\Users\user\Desktop\FundooNotes\FundooNotes\src\services\/note.service.js:4:27)
    at tryCatch (C:\Users\user\Desktop\FundooNotes\FundooNotes\node_modules\@babel\runtime\helpers\regeneratorRuntime.js:86:17)
    at Generator._invoke (C:\Users\user\Desktop\FundooNotes\FundooNotes\node_modules\@babel\runtime\helpers\regeneratorRuntime.js:66:24)
    at Generator.next (C:\Users\user\Desktop\FundooNotes\FundooNotes\node_modules\@babel\runtime\helpers\regeneratorRuntime.js:117:21)
    at asyncGeneratorStep (C:\Users\user\Desktop\FundooNotes\FundooNotes\node_modules\@babel\runtime\helpers\asyncToGenerator.js:3:24)
    at _next (C:\Users\user\Desktop\FundooNotes\FundooNotes\node_modules\@babel\runtime\helpers\asyncToGenerator.js:25:9)
    at C:\Users\user\Desktop\FundooNotes\FundooNotes\node_modules\@babel\runtime\helpers\asyncToGenerator.js:32:7
    at new Promise (<anonymous>)
    at Object.<anonymous> (C:\Users\user\Desktop\FundooNotes\FundooNotes\node_modules\@babel\runtime\helpers\asyncToGenerator.js:21:12)
    at Object.createNote (C:\Users\user\Desktop\FundooNotes\FundooNotes\src\services\/note.service.js:4:24)
    at _callee$ (C:\Users\user\Desktop\FundooNotes\FundooNotes\src\controllers\/note.controller.js:6:38)
    at tryCatch (C:\Users\user\Desktop\FundooNotes\FundooNotes\node_modules\@babel\runtime\helpers\regeneratorRuntime.js:86:17)
    at Generator._invoke (C:\Users\user\Desktop\FundooNotes\FundooNotes\node_modules\@babel\runtime\helpers\regeneratorRuntime.js:66:24)
    at Generator.next (C:\Users\user\Desktop\FundooNotes\FundooNotes\node_modules\@babel\runtime\helpers\regeneratorRuntime.js:117:21)
    at asyncGeneratorStep (C:\Users\user\Desktop\FundooNotes\FundooNotes\node_modules\@babel\runtime\helpers\asyncToGenerator.js:3:24)
    at _next (C:\Users\user\Desktop\FundooNotes\FundooNotes\node_modules\@babel\runtime\helpers\asyncToGenerator.js:25:9) 
    url - /api/v1/notes 
    method - POST 
    IP - ::1
   {"timestamp":"2022-05-30T07:11:44.947Z"}
error: 
    status - 500 
    message - ReferenceError: User is not defined
    at _callee$ (C:\Users\user\Desktop\FundooNotes\FundooNotes\src\services\/note.service.js:4:27)
    at tryCatch (C:\Users\user\Desktop\FundooNotes\FundooNotes\node_modules\@babel\runtime\helpers\regeneratorRuntime.js:86:17)
    at Generator._invoke (C:\Users\user\Desktop\FundooNotes\FundooNotes\node_modules\@babel\runtime\helpers\regeneratorRuntime.js:66:24)
    at Generator.next (C:\Users\user\Desktop\FundooNotes\FundooNotes\node_modules\@babel\runtime\helpers\regeneratorRuntime.js:117:21)
    at asyncGeneratorStep (C:\Users\user\Desktop\FundooNotes\FundooNotes\node_modules\@babel\runtime\helpers\asyncToGenerator.js:3:24)
    at _next (C:\Users\user\Desktop\FundooNotes\FundooNotes\node_modules\@babel\runtime\helpers\asyncToGenerator.js:25:9)
    at C:\Users\user\Desktop\FundooNotes\FundooNotes\node_modules\@babel\runtime\helpers\asyncToGenerator.js:32:7
    at new Promise (<anonymous>)
    at Object.<anonymous> (C:\Users\user\Desktop\FundooNotes\FundooNotes\node_modules\@babel\runtime\helpers\asyncToGenerator.js:21:12)
    at Object.createNote (C:\Users\user\Desktop\FundooNotes\FundooNotes\src\services\/note.service.js:4:24)
    at _callee$ (C:\Users\user\Desktop\FundooNotes\FundooNotes\src\controllers\/note.controller.js:6:38)
    at tryCatch (C:\Users\user\Desktop\FundooNotes\FundooNotes\node_modules\@babel\runtime\helpers\regeneratorRuntime.js:86:17)
    at Generator._invoke (C:\Users\user\Desktop\FundooNotes\FundooNotes\node_modules\@babel\runtime\helpers\regeneratorRuntime.js:66:24)
    at Generator.next (C:\Users\user\Desktop\FundooNotes\FundooNotes\node_modules\@babel\runtime\helpers\regeneratorRuntime.js:117:21)
    at asyncGeneratorStep (C:\Users\user\Desktop\FundooNotes\FundooNotes\node_modules\@babel\runtime\helpers\asyncToGenerator.js:3:24)
    at _next (C:\Users\user\Desktop\FundooNotes\FundooNotes\node_modules\@babel\runtime\helpers\asyncToGenerator.js:25:9) 
    url - /api/v1/notes 
    method - POST 
    IP - ::1
   {"timestamp":"2022-05-30T08:09:27.494Z"}
info: Server started at http://localhost:3000/api/v1/ {"timestamp":"2022-05-30T08:10:16.661Z"}
info: Connected to the database. {"timestamp":"2022-05-30T08:10:16.848Z"}
info: Server started at http://localhost:3000/api/v1/ {"timestamp":"2022-05-30T08:54:44.597Z"}
info: Connected to the database. {"timestamp":"2022-05-30T08:54:44.655Z"}
info: Server started at http://localhost:3000/api/v1/ {"timestamp":"2022-05-30T08:56:22.117Z"}
info: Connected to the database. {"timestamp":"2022-05-30T08:56:22.207Z"}
info: Server started at http://localhost:3000/api/v1/ {"timestamp":"2022-05-30T08:56:40.759Z"}
info: Connected to the database. {"timestamp":"2022-05-30T08:56:41.080Z"}
info: Server started at http://localhost:3000/api/v1/ {"timestamp":"2022-05-30T08:56:58.918Z"}
info: Server started at http://localhost:3000/api/v1/ {"timestamp":"2022-05-30T08:57:08.388Z"}
info: Connected to the database. {"timestamp":"2022-05-30T08:57:08.490Z"}
info: Server started at http://localhost:3000/api/v1/ {"timestamp":"2022-05-30T08:58:44.851Z"}
info: Connected to the database. {"timestamp":"2022-05-30T08:58:44.954Z"}
info: Server started at http://localhost:3000/api/v1/ {"timestamp":"2022-05-30T08:59:04.981Z"}
info: Connected to the database. {"timestamp":"2022-05-30T08:59:05.066Z"}
info: Server started at http://localhost:3000/api/v1/ {"timestamp":"2022-05-30T08:59:23.457Z"}
info: Connected to the database. {"timestamp":"2022-05-30T08:59:23.564Z"}
info: Server started at http://localhost:3000/api/v1/ {"timestamp":"2022-05-30T09:00:41.473Z"}
info: Connected to the database. {"timestamp":"2022-05-30T09:00:41.551Z"}
info: Server started at http://localhost:3000/api/v1/ {"timestamp":"2022-05-30T09:00:53.666Z"}
info: Connected to the database. {"timestamp":"2022-05-30T09:00:53.758Z"}
info: Server started at http://localhost:3000/api/v1/ {"timestamp":"2022-05-30T09:01:14.227Z"}
info: Connected to the database. {"timestamp":"2022-05-30T09:01:14.333Z"}
info: Server started at http://localhost:3000/api/v1/ {"timestamp":"2022-05-30T09:04:12.312Z"}
info: Connected to the database. {"timestamp":"2022-05-30T09:04:12.412Z"}
info: Server started at http://localhost:3000/api/v1/ {"timestamp":"2022-05-30T09:05:07.856Z"}
info: Connected to the database. {"timestamp":"2022-05-30T09:05:07.954Z"}
info: Server started at http://localhost:3000/api/v1/ {"timestamp":"2022-05-30T09:06:13.007Z"}
info: Connected to the database. {"timestamp":"2022-05-30T09:06:13.074Z"}
info: Server started at http://localhost:3000/api/v1/ {"timestamp":"2022-05-30T09:07:39.805Z"}
info: Connected to the database. {"timestamp":"2022-05-30T09:07:39.908Z"}
info: Server started at http://localhost:3000/api/v1/ {"timestamp":"2022-05-30T09:08:04.096Z"}
info: Connected to the database. {"timestamp":"2022-05-30T09:08:04.187Z"}
info: Server started at http://localhost:3000/api/v1/ {"timestamp":"2022-05-30T09:11:32.045Z"}
info: Connected to the database. {"timestamp":"2022-05-30T09:11:32.117Z"}
info: Server started at http://localhost:3000/api/v1/ {"timestamp":"2022-05-30T09:13:31.246Z"}
info: Connected to the database. {"timestamp":"2022-05-30T09:13:31.316Z"}
info: Server started at http://localhost:3000/api/v1/ {"timestamp":"2022-05-30T09:15:03.093Z"}
info: Connected to the database. {"timestamp":"2022-05-30T09:15:03.193Z"}
error: 
    status - 500 
    message - ReferenceError: UserService is not defined
    at _callee3$ (C:\Users\user\Desktop\FundooNotes\FundooNotes\src\controllers\/note.controller.js:30:27)
    at tryCatch (C:\Users\user\Desktop\FundooNotes\FundooNotes\node_modules\@babel\runtime\helpers\regeneratorRuntime.js:86:17)
    at Generator._invoke (C:\Users\user\Desktop\FundooNotes\FundooNotes\node_modules\@babel\runtime\helpers\regeneratorRuntime.js:66:24)
    at Generator.next (C:\Users\user\Desktop\FundooNotes\FundooNotes\node_modules\@babel\runtime\helpers\regeneratorRuntime.js:117:21)
    at asyncGeneratorStep (C:\Users\user\Desktop\FundooNotes\FundooNotes\node_modules\@babel\runtime\helpers\asyncToGenerator.js:3:24)
    at _next (C:\Users\user\Desktop\FundooNotes\FundooNotes\node_modules\@babel\runtime\helpers\asyncToGenerator.js:25:9)
    at C:\Users\user\Desktop\FundooNotes\FundooNotes\node_modules\@babel\runtime\helpers\asyncToGenerator.js:32:7
    at new Promise (<anonymous>)
    at C:\Users\user\Desktop\FundooNotes\FundooNotes\node_modules\@babel\runtime\helpers\asyncToGenerator.js:21:12
    at updateNote (C:\Users\user\Desktop\FundooNotes\FundooNotes\src\controllers\/note.controller.js:30:24)
    at Layer.handle [as handle_request] (C:\Users\user\Desktop\FundooNotes\FundooNotes\node_modules\express\lib\router\layer.js:95:5)
    at next (C:\Users\user\Desktop\FundooNotes\FundooNotes\node_modules\express\lib\router\route.js:144:13)
    at Route.dispatch (C:\Users\user\Desktop\FundooNotes\FundooNotes\node_modules\express\lib\router\route.js:114:3)
    at Layer.handle [as handle_request] (C:\Users\user\Desktop\FundooNotes\FundooNotes\node_modules\express\lib\router\layer.js:95:5)
    at C:\Users\user\Desktop\FundooNotes\FundooNotes\node_modules\express\lib\router\index.js:284:15
    at param (C:\Users\user\Desktop\FundooNotes\FundooNotes\node_modules\express\lib\router\index.js:365:14) 
    url - /api/v1/notes/62947bfc2d56650e080715d4 
    method - PUT 
    IP - ::1
   {"timestamp":"2022-05-30T09:23:26.458Z"}
info: Server started at http://localhost:3000/api/v1/ {"timestamp":"2022-05-30T09:24:28.660Z"}
info: Connected to the database. {"timestamp":"2022-05-30T09:24:28.753Z"}
error: 
    status - 500 
    message - ReferenceError: User is not defined
    at _callee4$ (C:\Users\user\Desktop\FundooNotes\FundooNotes\src\services\/note.service.js:27:27)
    at tryCatch (C:\Users\user\Desktop\FundooNotes\FundooNotes\node_modules\@babel\runtime\helpers\regeneratorRuntime.js:86:17)
    at Generator._invoke (C:\Users\user\Desktop\FundooNotes\FundooNotes\node_modules\@babel\runtime\helpers\regeneratorRuntime.js:66:24)
    at Generator.next (C:\Users\user\Desktop\FundooNotes\FundooNotes\node_modules\@babel\runtime\helpers\regeneratorRuntime.js:117:21)
    at asyncGeneratorStep (C:\Users\user\Desktop\FundooNotes\FundooNotes\node_modules\@babel\runtime\helpers\asyncToGenerator.js:3:24)
    at _next (C:\Users\user\Desktop\FundooNotes\FundooNotes\node_modules\@babel\runtime\helpers\asyncToGenerator.js:25:9)
    at C:\Users\user\Desktop\FundooNotes\FundooNotes\node_modules\@babel\runtime\helpers\asyncToGenerator.js:32:7
    at new Promise (<anonymous>)
    at Object.<anonymous> (C:\Users\user\Desktop\FundooNotes\FundooNotes\node_modules\@babel\runtime\helpers\asyncToGenerator.js:21:12)
    at Object.deleteUser (C:\Users\user\Desktop\FundooNotes\FundooNotes\src\services\/note.service.js:27:24)
    at _callee4$ (C:\Users\user\Desktop\FundooNotes\FundooNotes\src\controllers\/note.controller.js:45:25)
    at tryCatch (C:\Users\user\Desktop\FundooNotes\FundooNotes\node_modules\@babel\runtime\helpers\regeneratorRuntime.js:86:17)
    at Generator._invoke (C:\Users\user\Desktop\FundooNotes\FundooNotes\node_modules\@babel\runtime\helpers\regeneratorRuntime.js:66:24)
    at Generator.next (C:\Users\user\Desktop\FundooNotes\FundooNotes\node_modules\@babel\runtime\helpers\regeneratorRuntime.js:117:21)
    at asyncGeneratorStep (C:\Users\user\Desktop\FundooNotes\FundooNotes\node_modules\@babel\runtime\helpers\asyncToGenerator.js:3:24)
    at _next (C:\Users\user\Desktop\FundooNotes\FundooNotes\node_modules\@babel\runtime\helpers\asyncToGenerator.js:25:9) 
    url - /api/v1/notes/62947bfc2d56650e080715d4 
    method - DELETE 
    IP - ::1
   {"timestamp":"2022-05-30T09:26:00.612Z"}
info: Server started at http://localhost:3000/api/v1/ {"timestamp":"2022-05-30T09:26:25.611Z"}
info: Connected to the database. {"timestamp":"2022-05-30T09:26:25.687Z"}
