info: Server started at http://localhost:3000/api/v1/ {"timestamp":"2022-05-27T03:06:14.256Z"}
info: Connected to the database. {"timestamp":"2022-05-27T03:06:14.332Z"}
info: Server started at http://localhost:3000/api/v1/ {"timestamp":"2022-05-27T03:14:41.180Z"}
info: Connected to the database. {"timestamp":"2022-05-27T03:14:41.248Z"}
error: 
    status - 500 
    message - Error: Password not match
    at _callee3$ (C:\Users\user\Desktop\FundooNotes\FundooNotes\src\services\/user.service.js:22:13)
    at tryCatch (C:\Users\user\Desktop\FundooNotes\FundooNotes\node_modules\@babel\runtime\helpers\regeneratorRuntime.js:86:17)
    at Generator._invoke (C:\Users\user\Desktop\FundooNotes\FundooNotes\node_modules\@babel\runtime\helpers\regeneratorRuntime.js:66:24)
    at Generator.next (C:\Users\user\Desktop\FundooNotes\FundooNotes\node_modules\@babel\runtime\helpers\regeneratorRuntime.js:117:21)
    at asyncGeneratorStep (C:\Users\user\Desktop\FundooNotes\FundooNotes\node_modules\@babel\runtime\helpers\asyncToGenerator.js:3:24)
    at _next (C:\Users\user\Desktop\FundooNotes\FundooNotes\node_modules\@babel\runtime\helpers\asyncToGenerator.js:25:9)
    at processTicksAndRejections (node:internal/process/task_queues:96:5) 
    url - /api/v1/users/login 
    method - GET 
    IP - ::1
   {"timestamp":"2022-05-27T03:15:23.682Z"}
error: 
    status - 500 
    message - Error: User does not exist
    at _callee3$ (C:\Users\user\Desktop\FundooNotes\FundooNotes\src\services\/user.service.js:17:11)
    at tryCatch (C:\Users\user\Desktop\FundooNotes\FundooNotes\node_modules\@babel\runtime\helpers\regeneratorRuntime.js:86:17)
    at Generator._invoke (C:\Users\user\Desktop\FundooNotes\FundooNotes\node_modules\@babel\runtime\helpers\regeneratorRuntime.js:66:24)
    at Generator.next (C:\Users\user\Desktop\FundooNotes\FundooNotes\node_modules\@babel\runtime\helpers\regeneratorRuntime.js:117:21)
    at asyncGeneratorStep (C:\Users\user\Desktop\FundooNotes\FundooNotes\node_modules\@babel\runtime\helpers\asyncToGenerator.js:3:24)
    at _next (C:\Users\user\Desktop\FundooNotes\FundooNotes\node_modules\@babel\runtime\helpers\asyncToGenerator.js:25:9)
    at processTicksAndRejections (node:internal/process/task_queues:96:5) 
    url - /api/v1/users/login 
    method - GET 
    IP - ::1
   {"timestamp":"2022-05-27T03:15:41.383Z"}
info: Server started at http://localhost:3000/api/v1/ {"timestamp":"2022-05-27T03:20:36.591Z"}
info: Connected to the database. {"timestamp":"2022-05-27T03:20:36.652Z"}
info: Server started at http://localhost:3000/api/v1/ {"timestamp":"2022-05-27T03:25:09.434Z"}
info: Connected to the database. {"timestamp":"2022-05-27T03:25:09.497Z"}
error: 
    status - 500 
    message - ReferenceError: userData is not defined
    at _callee2$ (C:\Users\user\Desktop\FundooNotes\FundooNotes\src\services\/user.service.js:10:43)
    at tryCatch (C:\Users\user\Desktop\FundooNotes\FundooNotes\node_modules\@babel\runtime\helpers\regeneratorRuntime.js:86:17)
    at Generator._invoke (C:\Users\user\Desktop\FundooNotes\FundooNotes\node_modules\@babel\runtime\helpers\regeneratorRuntime.js:66:24)
    at Generator.next (C:\Users\user\Desktop\FundooNotes\FundooNotes\node_modules\@babel\runtime\helpers\regeneratorRuntime.js:117:21)
    at asyncGeneratorStep (C:\Users\user\Desktop\FundooNotes\FundooNotes\node_modules\@babel\runtime\helpers\asyncToGenerator.js:3:24)
    at _next (C:\Users\user\Desktop\FundooNotes\FundooNotes\node_modules\@babel\runtime\helpers\asyncToGenerator.js:25:9)
    at C:\Users\user\Desktop\FundooNotes\FundooNotes\node_modules\@babel\runtime\helpers\asyncToGenerator.js:32:7
    at new Promise (<anonymous>)
    at Object.<anonymous> (C:\Users\user\Desktop\FundooNotes\FundooNotes\node_modules\@babel\runtime\helpers\asyncToGenerator.js:21:12)
    at Object.registerUser (C:\Users\user\Desktop\FundooNotes\FundooNotes\src\services\/user.service.js:9:26)
    at _callee2$ (C:\Users\user\Desktop\FundooNotes\FundooNotes\src\controllers\/user.controller.js:25:36)
    at tryCatch (C:\Users\user\Desktop\FundooNotes\FundooNotes\node_modules\@babel\runtime\helpers\regeneratorRuntime.js:86:17)
    at Generator._invoke (C:\Users\user\Desktop\FundooNotes\FundooNotes\node_modules\@babel\runtime\helpers\regeneratorRuntime.js:66:24)
    at Generator.next (C:\Users\user\Desktop\FundooNotes\FundooNotes\node_modules\@babel\runtime\helpers\regeneratorRuntime.js:117:21)
    at asyncGeneratorStep (C:\Users\user\Desktop\FundooNotes\FundooNotes\node_modules\@babel\runtime\helpers\asyncToGenerator.js:3:24)
    at _next (C:\Users\user\Desktop\FundooNotes\FundooNotes\node_modules\@babel\runtime\helpers\asyncToGenerator.js:25:9) 
    url - /api/v1/users/signup 
    method - POST 
    IP - ::1
   {"timestamp":"2022-05-27T03:25:14.458Z"}
info: Server started at http://localhost:3000/api/v1/ {"timestamp":"2022-05-27T03:26:01.070Z"}
info: Connected to the database. {"timestamp":"2022-05-27T03:26:01.153Z"}
info: Server started at http://localhost:3000/api/v1/ {"timestamp":"2022-05-27T03:27:48.409Z"}
info: Connected to the database. {"timestamp":"2022-05-27T03:27:48.499Z"}
error: 
    status - 500 
    message - Error: User already exist
    at _callee2$ (C:\Users\user\Desktop\FundooNotes\FundooNotes\src\services\/user.service.js:15:11)
    at tryCatch (C:\Users\user\Desktop\FundooNotes\FundooNotes\node_modules\@babel\runtime\helpers\regeneratorRuntime.js:86:17)
    at Generator._invoke (C:\Users\user\Desktop\FundooNotes\FundooNotes\node_modules\@babel\runtime\helpers\regeneratorRuntime.js:66:24)
    at Generator.next (C:\Users\user\Desktop\FundooNotes\FundooNotes\node_modules\@babel\runtime\helpers\regeneratorRuntime.js:117:21)
    at asyncGeneratorStep (C:\Users\user\Desktop\FundooNotes\FundooNotes\node_modules\@babel\runtime\helpers\asyncToGenerator.js:3:24)
    at _next (C:\Users\user\Desktop\FundooNotes\FundooNotes\node_modules\@babel\runtime\helpers\asyncToGenerator.js:25:9)
    at processTicksAndRejections (node:internal/process/task_queues:96:5) 
    url - /api/v1/users/signup 
    method - POST 
    IP - ::1
   {"timestamp":"2022-05-27T03:27:54.735Z"}
info: Server started at http://localhost:3000/api/v1/ {"timestamp":"2022-05-27T03:31:27.797Z"}
info: Connected to the database. {"timestamp":"2022-05-27T03:31:27.860Z"}
error: 
    status - 500 
    message - SyntaxError: Unexpected token , in JSON at position 77
    at JSON.parse (<anonymous>)
    at parse (C:\Users\user\Desktop\FundooNotes\FundooNotes\node_modules\body-parser\lib\types\json.js:89:19)
    at C:\Users\user\Desktop\FundooNotes\FundooNotes\node_modules\body-parser\lib\read.js:128:18
    at AsyncResource.runInAsyncScope (node:async_hooks:202:9)
    at invokeCallback (C:\Users\user\Desktop\FundooNotes\FundooNotes\node_modules\raw-body\index.js:231:16)
    at done (C:\Users\user\Desktop\FundooNotes\FundooNotes\node_modules\raw-body\index.js:220:7)
    at IncomingMessage.onEnd (C:\Users\user\Desktop\FundooNotes\FundooNotes\node_modules\raw-body\index.js:280:7)
    at IncomingMessage.emit (node:events:539:35)
    at IncomingMessage.emit (node:domain:475:12)
    at endReadableNT (node:internal/streams/readable:1345:12)
    at processTicksAndRejections (node:internal/process/task_queues:83:21) 
    url - /api/v1/users/signup 
    method - POST 
    IP - ::1
   {"timestamp":"2022-05-27T03:33:52.540Z"}
info: Server started at http://localhost:3000/api/v1/ {"timestamp":"2022-05-27T03:37:31.084Z"}
info: Connected to the database. {"timestamp":"2022-05-27T03:37:31.322Z"}
info: Server started at http://localhost:3000/api/v1/ {"timestamp":"2022-05-27T03:38:22.774Z"}
info: Connected to the database. {"timestamp":"2022-05-27T03:38:22.843Z"}
error: 
    status - 500 
    message - ValidationError: "email" must be a valid email 
    url - /api/v1/users/signup 
    method - POST 
    IP - ::1
   {"timestamp":"2022-05-27T03:38:40.762Z"}
info: Server started at http://localhost:3000/api/v1/ {"timestamp":"2022-05-27T03:40:09.586Z"}
info: Connected to the database. {"timestamp":"2022-05-27T03:40:09.660Z"}
error: 
    status - 500 
    message - ReferenceError: HttpStatus is not defined
    at newUserValidator (C:\Users\user\Desktop\FundooNotes\FundooNotes\src\validators\/user.validator.js:12:16)
    at Layer.handle [as handle_request] (C:\Users\user\Desktop\FundooNotes\FundooNotes\node_modules\express\lib\router\layer.js:95:5)
    at next (C:\Users\user\Desktop\FundooNotes\FundooNotes\node_modules\express\lib\router\route.js:144:13)
    at Route.dispatch (C:\Users\user\Desktop\FundooNotes\FundooNotes\node_modules\express\lib\router\route.js:114:3)
    at Layer.handle [as handle_request] (C:\Users\user\Desktop\FundooNotes\FundooNotes\node_modules\express\lib\router\layer.js:95:5)
    at C:\Users\user\Desktop\FundooNotes\FundooNotes\node_modules\express\lib\router\index.js:284:15
    at Function.process_params (C:\Users\user\Desktop\FundooNotes\FundooNotes\node_modules\express\lib\router\index.js:346:12)
    at next (C:\Users\user\Desktop\FundooNotes\FundooNotes\node_modules\express\lib\router\index.js:280:10)
    at Function.handle (C:\Users\user\Desktop\FundooNotes\FundooNotes\node_modules\express\lib\router\index.js:175:3)
    at router (C:\Users\user\Desktop\FundooNotes\FundooNotes\node_modules\express\lib\router\index.js:47:12)
    at Layer.handle [as handle_request] (C:\Users\user\Desktop\FundooNotes\FundooNotes\node_modules\express\lib\router\layer.js:95:5)
    at trim_prefix (C:\Users\user\Desktop\FundooNotes\FundooNotes\node_modules\express\lib\router\index.js:328:13)
    at C:\Users\user\Desktop\FundooNotes\FundooNotes\node_modules\express\lib\router\index.js:286:9
    at Function.process_params (C:\Users\user\Desktop\FundooNotes\FundooNotes\node_modules\express\lib\router\index.js:346:12)
    at next (C:\Users\user\Desktop\FundooNotes\FundooNotes\node_modules\express\lib\router\index.js:280:10)
    at Function.handle (C:\Users\user\Desktop\FundooNotes\FundooNotes\node_modules\express\lib\router\index.js:175:3) 
    url - /api/v1/users/signup 
    method - POST 
    IP - ::1
   {"timestamp":"2022-05-27T03:40:19.154Z"}
error: 
    status - 500 
    message - ReferenceError: HttpStatus is not defined
    at newUserValidator (C:\Users\user\Desktop\FundooNotes\FundooNotes\src\validators\/user.validator.js:12:16)
    at Layer.handle [as handle_request] (C:\Users\user\Desktop\FundooNotes\FundooNotes\node_modules\express\lib\router\layer.js:95:5)
    at next (C:\Users\user\Desktop\FundooNotes\FundooNotes\node_modules\express\lib\router\route.js:144:13)
    at Route.dispatch (C:\Users\user\Desktop\FundooNotes\FundooNotes\node_modules\express\lib\router\route.js:114:3)
    at Layer.handle [as handle_request] (C:\Users\user\Desktop\FundooNotes\FundooNotes\node_modules\express\lib\router\layer.js:95:5)
    at C:\Users\user\Desktop\FundooNotes\FundooNotes\node_modules\express\lib\router\index.js:284:15
    at Function.process_params (C:\Users\user\Desktop\FundooNotes\FundooNotes\node_modules\express\lib\router\index.js:346:12)
    at next (C:\Users\user\Desktop\FundooNotes\FundooNotes\node_modules\express\lib\router\index.js:280:10)
    at Function.handle (C:\Users\user\Desktop\FundooNotes\FundooNotes\node_modules\express\lib\router\index.js:175:3)
    at router (C:\Users\user\Desktop\FundooNotes\FundooNotes\node_modules\express\lib\router\index.js:47:12)
    at Layer.handle [as handle_request] (C:\Users\user\Desktop\FundooNotes\FundooNotes\node_modules\express\lib\router\layer.js:95:5)
    at trim_prefix (C:\Users\user\Desktop\FundooNotes\FundooNotes\node_modules\express\lib\router\index.js:328:13)
    at C:\Users\user\Desktop\FundooNotes\FundooNotes\node_modules\express\lib\router\index.js:286:9
    at Function.process_params (C:\Users\user\Desktop\FundooNotes\FundooNotes\node_modules\express\lib\router\index.js:346:12)
    at next (C:\Users\user\Desktop\FundooNotes\FundooNotes\node_modules\express\lib\router\index.js:280:10)
    at Function.handle (C:\Users\user\Desktop\FundooNotes\FundooNotes\node_modules\express\lib\router\index.js:175:3) 
    url - /api/v1/users/signup 
    method - POST 
    IP - ::1
   {"timestamp":"2022-05-27T03:40:24.374Z"}
info: Server started at http://localhost:3000/api/v1/ {"timestamp":"2022-05-27T03:41:33.308Z"}
info: Connected to the database. {"timestamp":"2022-05-27T03:41:33.421Z"}
info: Server started at http://localhost:3000/api/v1/ {"timestamp":"2022-05-27T03:44:07.296Z"}
info: Connected to the database. {"timestamp":"2022-05-27T03:44:07.359Z"}
info: Server started at http://localhost:3000/api/v1/ {"timestamp":"2022-05-27T03:46:18.276Z"}
info: Connected to the database. {"timestamp":"2022-05-27T03:46:18.341Z"}
